import { Person } from "@/core/person/person.entity";

export const persons: Person[] = [
  new Person({
    id: "1",
    firstname: "Jean",
    lastname: "Dupont",
    nicknames: ["JD"],
    gender: "Male",
    relation: "Friend",
    createdAt: new Date("2021-03-15"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "2",
    firstname: "Marie",
    lastname: "Martin",
    nicknames: ["Mimi"],
    gender: "Female",
    relation: "Professional acquaintance",
    createdAt: new Date("2021-05-22"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "3",
    firstname: "Pierre",
    lastname: "Bernard",
    nicknames: ["Pitou"],
    gender: "Male",
    relation: "Business mate",
    createdAt: new Date("2021-07-10"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "4",
    firstname: "Sophie",
    lastname: "Petit",
    nicknames: ["So"],
    gender: "Female",
    relation: "Private acquaintance",
    createdAt: new Date("2021-09-03"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "5",
    firstname: "Thomas",
    lastname: "Robert",
    nicknames: ["Tom"],
    gender: "Male",
    relation: "Friend",
    createdAt: new Date("2021-11-18"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "6",
    firstname: "Julie",
    lastname: "Richard",
    nicknames: ["Juju"],
    gender: "Female",
    relation: "Professional acquaintance",
    createdAt: new Date("2022-01-25"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "7",
    firstname: "Lucas",
    lastname: "Durand",
    nicknames: ["Luke"],
    gender: "Male",
    relation: "Business mate",
    createdAt: new Date("2022-03-12"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "8",
    firstname: "Emma",
    lastname: "Dubois",
    nicknames: ["Em"],
    gender: "Female",
    relation: "Private acquaintance",
    createdAt: new Date("2022-05-30"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "9",
    firstname: "Hugo",
    lastname: "Moreau",
    nicknames: ["Hug"],
    gender: "Male",
    relation: "Friend",
    createdAt: new Date("2022-08-14"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "10",
    firstname: "Chloé",
    lastname: "Laurent",
    nicknames: ["Chlo"],
    gender: "Female",
    relation: "Professional acquaintance",
    createdAt: new Date("2022-10-05"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "11",
    firstname: "Nathan",
    lastname: "Simon",
    nicknames: ["Nate"],
    gender: "Male",
    relation: "Business mate",
    createdAt: new Date("2022-12-20"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "12",
    firstname: "Léa",
    lastname: "Michel",
    nicknames: ["Lé"],
    gender: "Female",
    relation: "Private acquaintance",
    createdAt: new Date("2023-02-08"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "13",
    firstname: "Maxime",
    lastname: "Lefebvre",
    nicknames: ["Max"],
    gender: "Male",
    relation: "Friend",
    createdAt: new Date("2023-04-17"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "14",
    firstname: "Manon",
    lastname: "Leroy",
    nicknames: ["Man"],
    gender: "Female",
    relation: "Professional acquaintance",
    createdAt: new Date("2023-06-22"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "15",
    firstname: "Enzo",
    lastname: "Roux",
    nicknames: ["Zozo"],
    gender: "Male",
    relation: "Business mate",
    createdAt: new Date("2023-08-09"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "16",
    firstname: "Camille",
    lastname: "David",
    nicknames: ["Cami"],
    gender: "Female",
    relation: "Private acquaintance",
    createdAt: new Date("2023-10-14"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "17",
    firstname: "Louis",
    lastname: "Bertrand",
    nicknames: ["Lou"],
    gender: "Male",
    relation: "Friend",
    createdAt: new Date("2023-12-01"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "18",
    firstname: "Sarah",
    lastname: "Morel",
    nicknames: ["Sara"],
    gender: "Female",
    relation: "Professional acquaintance",
    createdAt: new Date("2024-01-15"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "19",
    firstname: "Gabriel",
    lastname: "Fournier",
    nicknames: ["Gaby"],
    gender: "Male",
    relation: "Business mate",
    createdAt: new Date("2024-02-28"),
    channels: [],
    milestones: [],
  }),
  new Person({
    id: "20",
    firstname: "Zoé",
    lastname: "Girard",
    nicknames: ["Zoz"],
    gender: "Female",
    relation: "Private acquaintance",
    createdAt: new Date("2024-03-10"),
    channels: [],
    milestones: [],
  }),
];
